-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 13:15:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema all
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema all
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `all` DEFAULT CHARACTER SET latin1 ;
USE `all` ;

-- -----------------------------------------------------
-- Table `all`.`produto_nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`produto_nf` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `qtd_item` INT(11) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `id_produto` INT(11) NULL DEFAULT NULL,
  `valor_icms` FLOAT NULL DEFAULT NULL,
  `valor_ipi` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`servico_nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`servico_nf` (
  `id_servico` INT(11) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `valor_iss` FLOAT NULL DEFAULT NULL,
  `valor_unitario` FLOAT NULL DEFAULT NULL,
  `meses` INT(11) NULL DEFAULT NULL,
  `id_nfservico` INT NULL,
  `servico_nfcol` VARCHAR(45) NULL,
  `id_nf` INT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_centro_custo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_centro_custo` (
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(45) NULL DEFAULT NULL,
  `fantasia` VARCHAR(45) NULL DEFAULT NULL,
  `longradouro` VARCHAR(45) NULL DEFAULT NULL,
  `nro` INT(11) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_estadual` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_municipal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_cliente_fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_cliente_fisico` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `data_nasc` DATE NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `telefone` VARCHAR(40) NULL DEFAULT NULL,
  `id_endereco` VARCHAR(45) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_cliente_juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_cliente_juridico` (
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `incricao_estadual` VARCHAR(40) NULL DEFAULT NULL,
  `id_endereco` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_default`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_default` (
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `valor` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_endereco` (
  `estado` VARCHAR(40) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `rua` VARCHAR(40) NULL DEFAULT NULL,
  `numero` VARCHAR(40) NULL DEFAULT NULL,
  `complemento` VARCHAR(40) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_funcionario` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `id` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`notafiscal_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal_saida` (
  `data_emissao` DATE NULL DEFAULT NULL,
  `id_nf` INT NULL DEFAULT NULL,
  `cfop` INT(11) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `dados_adicionais` VARCHAR(40) NULL DEFAULT NULL,
  `estado` VARCHAR(40) NULL DEFAULT NULL,
  `serie` VARCHAR(40) NULL DEFAULT NULL,
  `insc_estadual` VARCHAR(40) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `val_icms` FLOAT NULL DEFAULT NULL,
  `val_ipi` FLOAT NULL DEFAULT NULL,
  `natureza_op` VARCHAR(40) NULL DEFAULT NULL,
  `id_nfsaida` INT NULL,
  `cod_contabil` VARCHAR(35) NULL,
  `procedencia` VARCHAR(100) NULL,
  `emitente` VARCHAR(100) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`notafiscal_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal_servico` (
  `data_emissao` DATE NULL DEFAULT NULL,
  `cfop` VARCHAR(4) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `dados_adicionais` VARCHAR(40) NULL DEFAULT NULL,
  `estado` VARCHAR(40) NULL DEFAULT NULL,
  `serie` BIT(1) NULL DEFAULT NULL,
  `insc_estadual` VARCHAR(40) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `val_iss` FLOAT NULL DEFAULT NULL,
  `id_nfservico` INT NULL,
  `id_nf` INT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_ordem_expedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_ordem_expedicao` (
  `_status` VARCHAR(40) NULL DEFAULT NULL,
  `data_entrega` DATE NULL DEFAULT NULL,
  `id_vendedor` INT(11) NULL DEFAULT NULL,
  `id_pedido` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_pedido` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `_status` VARCHAR(40) NULL DEFAULT NULL,
  `_data` DATE NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(40) NULL DEFAULT NULL,
  `id_vendedor` INT(11) NULL DEFAULT NULL,
  `id_cliente` VARCHAR(14) NULL DEFAULT NULL,
  `tipo_pagamento` VARCHAR(40) NULL DEFAULT NULL,
  `pago` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_produto` (
  `id_produto` INT(11) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`ProdutoNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`ProdutoNota` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `qtd_item` INT(11) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `id_produto` INT(11) NULL DEFAULT NULL,
  `valor_unitario` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_servico` (
  `id_servico` VARCHAR(40) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_servico_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_servico_pedido` (
  `id_servico` INT(11) NULL DEFAULT NULL,
  `id_pedido` INT(11) NULL DEFAULT NULL,
  `meses_duracao` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`notafiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal` (
  `id_nf` INT NOT NULL,
  `data_emissao` DATE NULL,
  `numero` VARCHAR(45) NULL,
  `cfop` INT NULL,
  `valor_total` FLOAT NULL,
  `dados_adicionais` VARCHAR(200) NULL,
  `uf` CHAR(2) NULL,
  `chave` VARCHAR(100) NULL,
  `status` BIT(1) NULL,
  PRIMARY KEY (`id_nf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `all`.`ServicoNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`ServicoNota` (
  `id_servico` INT NOT NULL,
  `valor_total` FLOAT NULL,
  `valor_unitario` FLOAT NULL,
  `descricao` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `valor_iss` FLOAT NULL,
  `mes` INT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
