-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 22:28:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema all
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema all
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `all` DEFAULT CHARACTER SET latin1 ;
USE `all` ;

-- -----------------------------------------------------
-- Table `all`.`notafiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal` (
  `id_nf` INT(11) NOT NULL AUTO_INCREMENT,
  `data_emissao` DATETIME NOT NULL,
  `numero` INT(11) NOT NULL,
  `serie` INT(11) NOT NULL,
  `cfop` INT(11) NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `dados_adicionais` VARCHAR(200) NULL DEFAULT NULL,
  `uf` CHAR(2) NOT NULL,
  `chave` VARCHAR(100) NOT NULL,
  `status` BIT(1) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `insc_estadual` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_nf`),
  UNIQUE INDEX `chave_UNIQUE` (`chave` ASC) VISIBLE,
  UNIQUE INDEX `id_nf_UNIQUE` (`id_nf` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`notafiscal_saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal_saida` (
  `id_nfsaida` INT(11) NOT NULL AUTO_INCREMENT,
  `id_nf` INT(11) NOT NULL,
  `especie` VARCHAR(80) NOT NULL,
  `subserie` VARCHAR(40) NOT NULL,
  `procedencia` VARCHAR(100) NOT NULL,
  `cod_contabil` VARCHAR(30) NOT NULL,
  `val_icms` FLOAT NOT NULL,
  `val_ipi` FLOAT NOT NULL,
  `emitente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_nfsaida`),
  UNIQUE INDEX `id_nf_UNIQUE` (`id_nf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`notafiscal_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`notafiscal_servico` (
  `id_nfservico` INT(11) NOT NULL AUTO_INCREMENT,
  `id_nf` INT(11) NOT NULL,
  `nome_tomador` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj_tomador` VARCHAR(14) NULL DEFAULT NULL,
  `val_iss` FLOAT NOT NULL,
  PRIMARY KEY (`id_nfservico`),
  UNIQUE INDEX `id_nf_UNIQUE` (`id_nf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`produtonota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`produtonota` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `qtd_item` INT(11) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `id_produto` INT(11) NULL DEFAULT NULL,
  `valor_unitario` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`servico_nf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`servico_nf` (
  `id_servico_nf` INT(11) NOT NULL AUTO_INCREMENT,
  `id_servico` INT(11) NOT NULL,
  `id_nf` INT(11) NOT NULL,
  `valor` FLOAT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `meses` INT(2) NOT NULL,
  PRIMARY KEY (`id_servico_nf`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`serviconota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`serviconota` (
  `id_servico` INT(11) NOT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `valor_unitario` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `valor_iss` FLOAT NULL DEFAULT NULL,
  `mes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_centro_custo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_centro_custo` (
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(45) NULL DEFAULT NULL,
  `fantasia` VARCHAR(45) NULL DEFAULT NULL,
  `longradouro` VARCHAR(45) NULL DEFAULT NULL,
  `nro` INT(11) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_estadual` VARCHAR(45) NULL DEFAULT NULL,
  `inscricao_municipal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_cliente_fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_cliente_fisico` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `data_nasc` DATE NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `telefone` VARCHAR(40) NULL DEFAULT NULL,
  `id_endereco` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_cliente_juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_cliente_juridico` (
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `incricao_estadual` VARCHAR(40) NULL DEFAULT NULL,
  `id_endereco` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_default`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_default` (
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `valor` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_endereco` (
  `estado` VARCHAR(40) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `rua` VARCHAR(40) NULL DEFAULT NULL,
  `numero` VARCHAR(40) NULL DEFAULT NULL,
  `complemento` VARCHAR(40) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_funcionario` (
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `id` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_ordem_expedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_ordem_expedicao` (
  `_status` VARCHAR(40) NULL DEFAULT NULL,
  `data_entrega` DATE NULL DEFAULT NULL,
  `id_vendedor` INT(11) NULL DEFAULT NULL,
  `id_pedido` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_pedido` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `_status` VARCHAR(40) NULL DEFAULT NULL,
  `_data` DATE NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(40) NULL DEFAULT NULL,
  `id_vendedor` INT(11) NULL DEFAULT NULL,
  `id_cliente` VARCHAR(14) NULL DEFAULT NULL,
  `tipo_pagamento` VARCHAR(40) NULL DEFAULT NULL,
  `pago` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_produto` (
  `id_produto` INT(11) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_produto_pedido` (
  `id_produto` INT(11) NULL DEFAULT NULL,
  `id_pedido` INT(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_servico` (
  `id_servico` VARCHAR(40) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `descricao` VARCHAR(40) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `all`.`tb_servico_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `all`.`tb_servico_pedido` (
  `id_servico` INT(11) NULL DEFAULT NULL,
  `id_pedido` INT(11) NULL DEFAULT NULL,
  `meses_duracao` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
